DELETE FROM DB_EVENTS;
-- initial synthetic db events
INSERT INTO DB_EVENTS(SRC_KEY, SRC_GROUP, ACTION_CODE, STATUS_CODE, EVENT_TS)
VALUES('customer1', 'customer', 'U', '0', CURRENT_TIMESTAMP);

INSERT INTO DB_EVENTS(SRC_KEY, SRC_GROUP, ACTION_CODE, STATUS_CODE, EVENT_TS)
VALUES('customer2', 'customer', 'U', '0', CURRENT_TIMESTAMP);

INSERT INTO DB_EVENTS(SRC_KEY, SRC_GROUP, ACTION_CODE, STATUS_CODE, EVENT_TS)
VALUES('order1', 'customerOrder', 'U', '0', CURRENT_TIMESTAMP);

INSERT INTO DB_EVENTS(SRC_KEY, SRC_GROUP, ACTION_CODE, STATUS_CODE, EVENT_TS)
VALUES('order2', 'customerOrder', 'U', '0', CURRENT_TIMESTAMP);

INSERT INTO DB_EVENTS(SRC_KEY, SRC_GROUP, ACTION_CODE, STATUS_CODE, EVENT_TS)
VALUES('order3', 'customerOrder', 'U', '0', CURRENT_TIMESTAMP);

INSERT INTO DB_EVENTS(SRC_KEY, SRC_GROUP, ACTION_CODE, STATUS_CODE, EVENT_TS)
VALUES('item1', 'item', 'U', '0', CURRENT_TIMESTAMP);

INSERT INTO DB_EVENTS(SRC_KEY, SRC_GROUP, ACTION_CODE, STATUS_CODE, EVENT_TS)
VALUES('item2', 'item', 'U', '0', CURRENT_TIMESTAMP);

INSERT INTO DB_EVENTS(SRC_KEY, SRC_GROUP, ACTION_CODE, STATUS_CODE, EVENT_TS)
VALUES('item3', 'item', 'U', '0', CURRENT_TIMESTAMP);
