DROP TABLE IF EXISTS DEMO;
-- create tables
CREATE TABLE DEMO(
	ID 			BIGINT NOT NULL AUTO_INCREMENT,
	MESSAGE		VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID)
);

-- DEMO triggers
DELIMITER $$
CREATE DEFINER = CURRENT_USER TRIGGER `DEMO_AFTER_INSERT` AFTER INSERT ON `DEMO` FOR EACH ROW
BEGIN
	INSERT INTO DB_EVENTS(SRC_KEY, SRC_GROUP, ACTION_CODE, STATUS_CODE, EVENT_TS)
	VALUES(NEW.ID, 'demo', 'I', '0', CURRENT_TIMESTAMP);
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER = CURRENT_USER TRIGGER `DEMO_AFTER_UPDATE` AFTER UPDATE ON `DEMO` FOR EACH ROW
BEGIN
	INSERT INTO DB_EVENTS(SRC_KEY, SRC_GROUP, ACTION_CODE, STATUS_CODE, EVENT_TS)
	VALUES(NEW.ID, 'demo', 'U', '0', CURRENT_TIMESTAMP);
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER = CURRENT_USER TRIGGER `DEMO_AFTER_DELETE` AFTER DELETE ON `DEMO` FOR EACH ROW
BEGIN
	INSERT INTO DB_EVENTS(SRC_KEY, SRC_GROUP, ACTION_CODE, STATUS_CODE, EVENT_TS)
	VALUES(OLD.ID, 'demo', 'D', '0', CURRENT_TIMESTAMP);
END$$
DELIMITER ;

DELETE FROM DB_EVENTS;

INSERT INTO DEMO(MESSAGE) VALUES('Hello Spring Day!!!');
INSERT INTO DEMO(MESSAGE) VALUES('Hello Chicago!!!');
INSERT INTO DEMO(MESSAGE) VALUES('SCS is AWSOME!!!');

SELECT * FROM DB_EVENTS;
