DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS ITEM;
DROP TABLE IF EXISTS CUSTOMER_ORDER;
DROP TABLE IF EXISTS ORDER_ITEM;
DROP TABLE IF EXISTS DB_EVENTS;

-- create tables
CREATE TABLE CUSTOMER(
	ID			VARCHAR(255) NOT NULL,
	NAME		VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE ITEM(
	ID			VARCHAR(255) NOT NULL,
	NAME		VARCHAR(255) NOT NULL,
	PRICE		DECIMAL(19, 2) NOT NULL,
	DESCRIPTION	VARCHAR(255),
	PRIMARY KEY(ID)
);

CREATE TABLE CUSTOMER_ORDER(
	ID			VARCHAR(255) NOT NULL,
	CUSTOMER_ID	VARCHAR(255) NOT NULL,
	ORDER_TS	TIMESTAMP NOT NULL,
	S_ADDRESS	VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE ORDER_ITEM(
	CUSTOMER_ORDER_ID	VARCHAR(255) NOT NULL,
	ITEM_ID				VARCHAR(255) NOT NULL,
	PRIMARY KEY(CUSTOMER_ORDER_ID, ITEM_ID)
);

CREATE TABLE DB_EVENTS(
	EVENT_ID 	BIGINT NOT NULL AUTO_INCREMENT,
	SRC_KEY		VARCHAR(255),
	SRC_GROUP	VARCHAR(255),
	ACTION_CODE	CHAR(1),
	STATUS_CODE	TINYINT,
	EVENT_TS	TIMESTAMP,
    PRIMARY KEY(EVENT_ID)
);

COMMIT;
